#!/bin/bash
# Script to extract and format Pokémon data using jq.

# Define data file
DATA_FILE="data.json"

jq -r '[.name, (.height / 10), (.weight / 10), (.weight / 10), .types[0].type.name] | @csv' "$DATA_FILE" | \
sed -E 's/^([^,]+),([^,]+),([^,]+),([^,]+)$/\u\1, \2, \3, \u\4/' | \
awk -F',' '{printf "%s is of type %s, weighs %.0.fkg, and is %.1fm tall.\n", $1, $4, $3, $2}'
