#!/bin/bash
# Use advanced text manipulatin tools to extract specific data from
# the API response.

jq -r '.name, .height, weight, .types[0].type.name' data.json | awk '{
  # Capitalize the first letter of the name and type
  name = toupper(substr($1,1,1)) substr($1,2)
  type = toupper(substr($4,1,1)) substr($4,2)

  # Convert height (dm to m) and weight (hg to kg)
  height_m = $2 / 10
  weight_kg = $3 / 10

  # Print the final formatted sentence
  printf "%s is of type %s, weighs %.0fkg, and is %.1fm tall.\n", name, type, weight_kg, height_m
}
